### ISSUE TITLE
ScannerModule: scanAreaD() rzuca NullPointerException przy próbie użycia

### ISSUE THREAD

**Issue by a-hor** [wjcsz/Space-Garbage-Collector#28]

**Comment by a-hor** [comment]
Po odkomentowaniu catchDebris() (linie 81-89 w Wardenclyffe):
`stop, start, fly, return, refuel, restock, catch, utilize, info, report, list, collectors, end
start
catch
choose a collector
0
Exception in thread "main" java.lang.NullPointerException
	at Edison.Wardenclyffe.catchDebris(Wardenclyffe.java:82)
	at Edison.Wardenclyffe.main(Wardenclyffe.java:177)

Process finished with exit code 1`

**Comment by Szczaleg** [comment]
Nie bede pushowac bo mam duzo niezapisanych zmian in progress, ale hotfix to linia 105 w scannermodule visible_map ma byc >= a nie ==

**Comment by Szczaleg** [comment]
Zauwazylerm ze nr linii moze byc wzgledny, chodzi o te linijke:
"if (visible_map[i][j] >= 1) {" (bylo == )
